-- MySQL Script generated by MySQL Workbench
-- Thu Nov 18 09:52:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sge` DEFAULT CHARACTER SET utf8 ;
USE `sge` ;

-- -----------------------------------------------------
-- Table `sge`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NULL,
  `cidade` VARCHAR(255) NULL,
  `uf` VARCHAR(2) NULL,
  `bairro` VARCHAR(255) NULL,
  `rua` VARCHAR(255) NULL,
  `complemento` VARCHAR(255) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sge`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NULL,
  `telefone_celular` VARCHAR(17) NULL,
  `telefone_contato` VARCHAR(17) NULL,
  `endereco_id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_endereco_idx` (`endereco_id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_endereco`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `sge`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sge`.`eletronico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`eletronico` (
  `id_eletronico` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(255) NULL,
  `marca` VARCHAR(255) NULL,
  `numero` VARCHAR(50) NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_eletronico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sge`.`cliente_eletronico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`cliente_eletronico` (
  `cliente_id_cliente` INT NOT NULL,
  `eletronico_id_eletronico` INT NOT NULL,
  PRIMARY KEY (`cliente_id_cliente`, `eletronico_id_eletronico`),
  INDEX `fk_cliente_has_eletronico_eletronico1_idx` (`eletronico_id_eletronico` ASC) VISIBLE,
  INDEX `fk_cliente_has_eletronico_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_eletronico_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `sge`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_eletronico_eletronico1`
    FOREIGN KEY (`eletronico_id_eletronico`)
    REFERENCES `sge`.`eletronico` (`id_eletronico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sge`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `nome_status` VARCHAR(255) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sge`.`tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`tecnico` (
  `id_tecnico` INT NOT NULL AUTO_INCREMENT,
  `nome_tecnico` VARCHAR(255) NULL,
  `telefone_tecnico` VARCHAR(17) NULL,
  `endereco_id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_tecnico`),
  INDEX `fk_tecnico_endereco1_idx` (`endereco_id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_tecnico_endereco1`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `sge`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sge`.`reparo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sge`.`reparo` (
  `id_reparo` INT NOT NULL AUTO_INCREMENT,
  `data_recebimento` DATE NULL,
  `data_previsao` DATE NULL,
  `data_entrega` DATE NULL,
  `observacao` VARCHAR(255) NULL,
  `mao_obra` FLOAT NULL,
  `custo_peca` FLOAT NULL,
  `valor_total` FLOAT NULL,
  `status_id_status` INT NOT NULL,
  `tecnico_id_tecnico` INT NOT NULL,
  `eletronico_id_eletronico` INT NOT NULL,
  PRIMARY KEY (`id_reparo`),
  INDEX `fk_reparo_eletronico1_idx` (`eletronico_id_eletronico` ASC) VISIBLE,
  INDEX `fk_reparo_status1_idx` (`status_id_status` ASC) VISIBLE,
  INDEX `fk_reparo_tecnico1_idx` (`tecnico_id_tecnico` ASC) VISIBLE,
  CONSTRAINT `fk_reparo_eletronico1`
    FOREIGN KEY (`eletronico_id_eletronico`)
    REFERENCES `sge`.`eletronico` (`id_eletronico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reparo_status1`
    FOREIGN KEY (`status_id_status`)
    REFERENCES `sge`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reparo_tecnico1`
    FOREIGN KEY (`tecnico_id_tecnico`)
    REFERENCES `sge`.`tecnico` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
